### ISSUE TITLE
UI-O-Matic Paging not working in 8.9.1

### ISSUE THREAD

**Issue by HevinPatel** [TimGeyssens/UIOMatic#174]
Hello,

We have used Umbraco 8.9.1 version, we used UI-O-Matic for the custom modules in backoffice, but we face issue in list view of the modules as mentioned below.

1) Paging not working
2) Filters not working

But if we clear the browser cookie/cache then it start working, but again if we move to any other Umbracode backoffice module and come back on the UI-O-Matic modules then it does not work, again if we do the same process then it start working.

As you requested I have added this as a bug over here.

**Comment by chrden** [comment]
Also confirmed paging and filtering working on Umbraco 8.6.4 with UIOMatic 3.1.1.

Tried with existing Chrome tab and Chrome Incognito tab to test the clear cookie/cache behaviour as mentioned about but both produced the same result.

If I use filter or paging, the results refresh always displays page 1

Let me know if you need any more info

**Comment by HevinPatel** [comment]
Here are the steps I have followed.

Created blank project with Umbraco 8.9.1 and Installed nuget packages for UI-O-Matic 3.1.1

Then created Model which suits to UI-O-Matic to show the records in List view and not as a tree.

Inserted few records to test the Paging and find that the paging is not working, then clear cache and cookie, so the system logged me out and ask for login again, After login it land me directly on the UI-O-Matic module as that was open before logout. 

It seems working fine as expected, but if I move to Content section once and then move back to the UI-O-Matic section, the paging again stop working for me.

I hope the provided details will help to investigate the issue further.

Thanks

**Comment by HevinPatel** [comment]
Additionally, I have tried the same thing with UIOMatic 8.6.4 and still facing the same issue, could you please provide me the project you have created and verified with the db backup so that we can try to review it at our end once with that project to compare and confirm nothing is missing in the project we have developed.

As for us the same issue is there in any browser (with or without incognito mode) and we have tried Umbraco 8.5.5, 8.6.4 and 8.9.1 the latest one to check the same thing and we are facing the issue in all the cases.

**Comment by pedrocruzfever** [comment]
Same here with Umbraco 8.9.1 and UI-O-Matic 3.1.1, with or without incognito mode, even going directly to the ui-o-matic list page.

![image](https://user-images.githubusercontent.com/48131197/102257440-a5dbda00-3f04-11eb-8526-646d75d1d066.png)

The parameters are always the same when I try to go to another page or try to search something (pageNumber:1 and searchTerm:[empty] )

thanks

**Comment by HevinPatel** [comment]
@pedrocruzfever I just want to confirm so you are having the same issues as me or it is working fine at your end.

As for me it is not working as expected.

**Comment by pedrocruzfever** [comment]
Hello @HevinPatel I'm having the exact same issues as you, but cleaning the cache/cookies won't solve me the problem

**Comment by HevinPatel** [comment]
@pedrocruzfever  it will work if you clear cookies/cache but not exactly as required. Follow below steps for the same.

Login to the Umbraco Backoffice, go to UIOMatic module, try to navigate from one page to another page in List view, it will not work. But except going anywhere else, clear your browser cache/cookies... once done try to navigate on other page from paging, it will log you out from the system, but once you login back it will redirect you on the UIOMatic page where you stands last, now if you change paging then it will work as expected.

But, now if you navigate to any other UIOMatic module and then come back to UIOMatic module then the paging will stop working again as before...

I have tried to dig into the possible issue but I was not able to identify and fix the same, but it looks like when it was not working I can see that the Page Number in the request was always passing value as a 1, but when it was working it passing the correct number of the Page, but the actual root cause I am unable to identify yet.

I hope @TimGeyssens or team will resolve and update us for the issue soon...

**Comment by TimGeyssens** [comment]
Hey all, I'll have some time next week to fix the issue... it's probably due to some storage we introduced (that remembers the filter)... so should be an easy fix

**Comment by TimGeyssens** [comment]
So in this file https://github.com/TimGeyssens/UIOMatic/blob/v3/src/UIOMatic/Web/UI/App_Plugins/UIOMatic/backoffice/uiomatic/list.controller.js

**Comment by HevinPatel** [comment]
Hi @TimGeyssens,

Please let us know once you apply fix for the issue.

Thanks

**Comment by HevinPatel** [comment]
Hi @TimGeyssens 

Have you looked in to the issue and possible fix? As we are planning to use the package in one of our project but we can't do that until we have the issue fixed.

Thanks

**Comment by TimGeyssens** [comment]
not yet... will try this year ;)

**Comment by HevinPatel** [comment]
@TimGeyssens Happy New Year, We are expecting some news with updates if you got time to look into it, as we have already started using the package in one of our project, but if the issue does not resolve then it will be a big disaster for us.

**Comment by TimGeyssens** [comment]
Thanks yes will look shortly ... also need to package in a project so...

**Comment by HevinPatel** [comment]
@TimGeyssens Please give some good news with the updates, we are still waiting for the updates and as mentioned we have already started using the package in one of our project, so please give us some updates on it as soon as possible.

**Comment by TimGeyssens** [comment]
Not yet @HevinPatel , if you want to have it fixed immedialty you can pay for the work? How much time does the tool save you? How much budget? How much are you willing to pay to have it fixed? Cheers, Tim

**Comment by pedrocruzfever** [comment]
@HevinPatel try using the previous version of list.controller.js, before the development of the state/storage functionality

https://raw.githubusercontent.com/TimGeyssens/UIOMatic/c8d20e9c5ed7fdc4410321c28a29c5e2ce9cd099/src/UIOMatic/Web/UI/App_Plugins/UIOMatic/backoffice/uiomatic/list.controller.js

I will also try to take a look at the latest version to see if am able to fix it....

**Comment by HevinPatel** [comment]
@pedrocruzfever thanks for the help, 

@pedrocruzfever & @TimGeyssens could you please let us know if there is possibility to store the Admin login user ID and current date in UIOMatic table, if so then please let us know how.

**Comment by TimGeyssens** [comment]
of course you can do that,  look at the docs for event model https://timgeyssens.gitbook.io/ui-o-matic/09.eventmodel

**Comment by HevinPatel** [comment]
@TimGeyssens  thanks for the link, is there any example code link that we can refer for the same.

**Comment by TimGeyssens** [comment]
Sure, this is for v7 but should be familiar http://www.nibble.be/?p=497

**Comment by tomschimmel** [comment]
@TimGeyssens, @HevinPatel and @pedrocruzfever, I've fixed this issue and created a pull request for it > https://github.com/TimGeyssens/UIOMatic/pull/178

**Comment by Vertigo093i** [comment]
Neither filtering nor sorting nor searching (nor paging - haven't able to verify) doesn't work.

**Comment by tomschimmel** [comment]
> Neither filtering nor sorting nor searching (nor paging - haven't able to verify) doesn't work.

@Vertigo093i have you pulled the latest changes from the v3 branch including the changes from the pending pull request? The changes haven't been merged yet by the owner of this repository so I guess that's why it's not working for you. Otherwise if you have the changes, try editing the version value in your clientdependency.config file. That's should clear the cache.

**Comment by Vertigo093i** [comment]
> have you pulled the latest changes from the v3 branch including the changes from the pending pull request?

@fungybytes I'm using the NuGet version of the plugin. Therefore the short answer is "no".
I've also tried with browser's DevTools being opened which should effectively disable caching.

**Comment by Vertigo093i** [comment]
@fungybytes I've tried your changes from the PR.
Paging, sorting and searching both do work while the filtering still doesn't.

/cc @TimGeyssens

**Comment by TimGeyssens** [comment]
fixed in pr from @fungybytes
